export const tags: string[] = [
  "Music",
  "Dance",
  "Painting",
  "Poetry",
  "Theatre",
  "Film",
  "Photography",
  "Sculpture",
  "Architecture",
  "Literature",
  "Drawing",
  "Digital Art",
  "Performance Art",
  "Installation Art",
  "Cinema",
  "Street Art",
  "Culinary Arts",
  "Fashion Design",
  "Graphic Design",
  "Conceptual Art",
  "Video Art",
  "Printmaking",
  "Animation",
  "Sound Art",
  "Mixed Media"
];